In [19]:
import pandas as pd

In [20]:
#loading top 50 original data and converting to data frame
top_25 = "/Users/grizzlyjenkins/Personal Documents/top_25_1.csv"
top_25_df = pd.read_csv(top_25)
top_25_df.sort_values('Rank', ascending=False)
top_25_df.head()

,Rank,FA #,A,FA Name,Country,Area,Region,Cansell,Position Code,12 mo,1 mo,AUC,1 mo assets in,12 mo assets in,1 mo assets out,12 mo assets out,1 mo new new,12 mo net new,Best Month
0,1.0,782084.0,19887.0,"Marcontell,Jennifer",US,24.0,24.0,1/31/00,NaN,"7,806,377","730,989","1,594,736,352","33,403,885","228,339,247","-11,093,666","-107,158,250","22,310,219","121,180,997",NaN
1,2.0,248635.0,8845.0,"Nelson,Troy",US,4.0,69.0,9/28/98,NaN,"6,934,218","677,282","809,997,238","6,313,028","74,585,733","-3,669,169","-62,898,723","2,643,860","11,687,010",NaN
2,3.0,500256.0,5002.0,"Finucan,Timothy",US,29.0,254.0,1/30/87,NaN,"4,972,185","524,957","770,154,107","7,298,579","75,127,769","-5,607,739","-39,439,097","1,690,840","35,688,672",Y
3,4.0,544454.0,5444.0,"Kolod,Glenn",US,11.0,265.0,5/22/92,NaN,"4,342,781","432,238","656,356,759","3,784,825","39,705,709","-3,050,762","-33,032,006","734,063","6,673,703",Y
4,5.0,119620.0,11962.0,"Kitchen,Jeffrey",US,27.0,198.0,11/2/98,GP,"4,286,516","404,032","529,138,710","4,005,883","56,945,542","-3,744,082","-31,926,492","261,801","25,019,051",Y

In [21]:
#loading Amy's top 25 design research and converting to data frame
top_25_design = "/Users/grizzlyjenkins/Personal Documents/top_25_d.csv"
top_25_design_df = pd.read_csv(top_25_design)
top_25_design_df.sort_values('Rank', ascending=False)
top_25_design_df.head()

,Rank,FA #,A,FA Name,Best Month,Standard Layout,Layout Details,Current FA Offices (Not including Conference),Total Offices,Conference used to host Client meetings,Office Size,Non- Standard Items,Non Standard Finishes Description,Notes
0,1,782084,19887,"Marcontell,Jennifer",NaN,No,Shared Real Estate Layout,1,11,Yes,3600,Yes,Custom plank/carpet/Glass partitions/lighting,NaN
1,2,248635,8845,"Nelson,Troy",NaN,No,"Two Adequate size office, 4 small",2,6,Yes,2600,Yes,Tile/Custom Carpet,NaN
2,3,500256,5002,"Finucan,Timothy",Y,Yes,GK expansion,3,7,Yes,1988,Yes,Tile/Custom Carpet/Wallpaper/Built Ins,NaN
3,4,544454,5444,"Kolod,Glenn",Y,Yes,Pass through conference to 2nd office,1,2,Yes,1186,Yes,Custom Carpet/Non-Standard Paint,NaN
4,5,119620,11962,"Kitchen,Jeffrey",Y,Yes,"(1) Large FA office, 2 small",2,3,Yes,1245,Yes,Non Standard Plank/Custom Carpet/Glass walls/B...,NaN

In [22]:
#mergin the previously loaded data frames
merged_data = pd.merge(top_25_df,top_25_design_df,on='A')
merged_data.head()

,Rank_x,FA #_x,A,FA Name_x,Country,Area,Region,Cansell,Position Code,12 mo,...,Best Month_y,Standard Layout,Layout Details,Current FA Offices (Not including Conference),Total Offices,Conference used to host Client meetings,Office Size,Non- Standard Items,Non Standard Finishes Description,Notes
0,1.0,782084.0,19887.0,"Marcontell,Jennifer",US,24.0,24.0,1/31/00,NaN,"7,806,377",...,NaN,No,Shared Real Estate Layout,1,11,Yes,3600,Yes,Custom plank/carpet/Glass partitions/lighting,NaN
1,2.0,248635.0,8845.0,"Nelson,Troy",US,4.0,69.0,9/28/98,NaN,"6,934,218",...,NaN,No,"Two Adequate size office, 4 small",2,6,Yes,2600,Yes,Tile/Custom Carpet,NaN
2,3.0,500256.0,5002.0,"Finucan,Timothy",US,29.0,254.0,1/30/87,NaN,"4,972,185",...,Y,Yes,GK expansion,3,7,Yes,1988,Yes,Tile/Custom Carpet/Wallpaper/Built Ins,NaN
3,4.0,544454.0,5444.0,"Kolod,Glenn",US,11.0,265.0,5/22/92,NaN,"4,342,781",...,Y,Yes,Pass through conference to 2nd office,1,2,Yes,1186,Yes,Custom Carpet/Non-Standard Paint,NaN
4,5.0,119620.0,11962.0,"Kitchen,Jeffrey",US,27.0,198.0,11/2/98,GP,"4,286,516",...,Y,Yes,"(1) Large FA office, 2 small",2,3,Yes,1245,Yes,Non Standard Plank/Custom Carpet/Glass walls/B...,NaN

In [23]:
#cleaning up column names
top_25_merged = merged_data.rename(columns={"FA #_x": "FA #",
                                   "FA Name_x": "FA Name"})
top_25_merged.head()

,Rank_x,FA #,A,FA Name,Country,Area,Region,Cansell,Position Code,12 mo,...,Best Month_y,Standard Layout,Layout Details,Current FA Offices (Not including Conference),Total Offices,Conference used to host Client meetings,Office Size,Non- Standard Items,Non Standard Finishes Description,Notes
0,1.0,782084.0,19887.0,"Marcontell,Jennifer",US,24.0,24.0,1/31/00,NaN,"7,806,377",...,NaN,No,Shared Real Estate Layout,1,11,Yes,3600,Yes,Custom plank/carpet/Glass partitions/lighting,NaN
1,2.0,248635.0,8845.0,"Nelson,Troy",US,4.0,69.0,9/28/98,NaN,"6,934,218",...,NaN,No,"Two Adequate size office, 4 small",2,6,Yes,2600,Yes,Tile/Custom Carpet,NaN
2,3.0,500256.0,5002.0,"Finucan,Timothy",US,29.0,254.0,1/30/87,NaN,"4,972,185",...,Y,Yes,GK expansion,3,7,Yes,1988,Yes,Tile/Custom Carpet/Wallpaper/Built Ins,NaN
3,4.0,544454.0,5444.0,"Kolod,Glenn",US,11.0,265.0,5/22/92,NaN,"4,342,781",...,Y,Yes,Pass through conference to 2nd office,1,2,Yes,1186,Yes,Custom Carpet/Non-Standard Paint,NaN
4,5.0,119620.0,11962.0,"Kitchen,Jeffrey",US,27.0,198.0,11/2/98,GP,"4,286,516",...,Y,Yes,"(1) Large FA office, 2 small",2,3,Yes,1245,Yes,Non Standard Plank/Custom Carpet/Glass walls/B...,NaN

In [25]:
#loading in physical locations report and converting to data frame
pl_report = "/Users/grizzlyjenkins/Personal Documents/pl_report.csv"
pl_df = pd.read_csv(pl_report)
pl_df.head()

,Branch #,Property Address,Suite,City,State,Zip,Country,Location Id,Original Occupancy,Lease Expiration,...,Flooring Year,Flooring Type,Flooring Non-Standard Description,Paint Year,Paint Color,Paint Non-Standard Description,HVAC Year,HVAC Description,Furniture Year,Furniture Description
0,1015.0,6235 Main St,NaN,Oliver,BC,V0H 1T0,CAN,1015.0,5/1/00,4/30/25,...,2004.0,Non-Standard/Custom,HARD WOOD FLOORING THROUGHOUT OFFICE,2004.0,SW Agreeable Gray/Custom EDJ Green (Pre 2008),NaN,NaN,NaN,2014.0,2014-1 task chairs (Hawthorn)\n2000-1 Endura F...
1,1023.0,70 James St,NaN,Parry Sound,ON,P2A 1T5,CAN,1023.0,4/1/00,3/31/25,...,2011.0,EDJ Standard – Digest (2009-2012),NaN,2011.0,BM Antique Parchment/Custom EDJ Green (2008-2009),NaN,NaN,NaN,2012.0,2012: 4 Rein guest chairs\n2000-1 Endura FA wo...
2,1024.0,38142 Cleveland Ave,102,Squamish,BC,V8B 0b1,CAN,113624.0,1/1/11,12/31/25,...,2011.0,EDJ Standard – Patcraft EDJ Custom (2012-2016),NaN,2011.0,SW Colony Buff/RockGarden (2009-Present),NaN,NaN,NaN,2000.0,2000-1 Endura FA workstation\n2000-1 Endura BO...
3,1027.0,25 King St,Unit B,Ingersoll,ON,N5C 2J2,CAN,1027.0,3/1/05,2/28/25,...,2015.0,EDJ Standard – Patcraft EDJ Custom (2012-2016),NaN,2015.0,SW Colony Buff/RockGarden (2009-Present),NaN,NaN,NaN,2017.0,2017-1 task chair (Hawthorn)\n2000-1 Endura FA...
4,1029.0,15160 Yonge St,1,Aurora,ON,L4G 1M2,CAN,136632.0,12/1/11,1/31/22,...,2020.0,EDJ Standard – LVP & Carpet Tile (2016-Present),NaN,2020.0,SW Colony Buff/RockGarden (2009-Present),NaN,NaN,NaN,2000.0,"STANDARD\n2012 - (4) Stack guest chairs, (1) H..."

In [28]:
#cleaning up column names
pl_df_clean = pl_df.rename(columns={"Branch #": "A"})
pl_df_clean.head()

,A,Property Address,Suite,City,State,Zip,Country,Location Id,Original Occupancy,Lease Expiration,...,Flooring Year,Flooring Type,Flooring Non-Standard Description,Paint Year,Paint Color,Paint Non-Standard Description,HVAC Year,HVAC Description,Furniture Year,Furniture Description
0,1015.0,6235 Main St,NaN,Oliver,BC,V0H 1T0,CAN,1015.0,5/1/00,4/30/25,...,2004.0,Non-Standard/Custom,HARD WOOD FLOORING THROUGHOUT OFFICE,2004.0,SW Agreeable Gray/Custom EDJ Green (Pre 2008),NaN,NaN,NaN,2014.0,2014-1 task chairs (Hawthorn)\n2000-1 Endura F...
1,1023.0,70 James St,NaN,Parry Sound,ON,P2A 1T5,CAN,1023.0,4/1/00,3/31/25,...,2011.0,EDJ Standard – Digest (2009-2012),NaN,2011.0,BM Antique Parchment/Custom EDJ Green (2008-2009),NaN,NaN,NaN,2012.0,2012: 4 Rein guest chairs\n2000-1 Endura FA wo...
2,1024.0,38142 Cleveland Ave,102,Squamish,BC,V8B 0b1,CAN,113624.0,1/1/11,12/31/25,...,2011.0,EDJ Standard – Patcraft EDJ Custom (2012-2016),NaN,2011.0,SW Colony Buff/RockGarden (2009-Present),NaN,NaN,NaN,2000.0,2000-1 Endura FA workstation\n2000-1 Endura BO...
3,1027.0,25 King St,Unit B,Ingersoll,ON,N5C 2J2,CAN,1027.0,3/1/05,2/28/25,...,2015.0,EDJ Standard – Patcraft EDJ Custom (2012-2016),NaN,2015.0,SW Colony Buff/RockGarden (2009-Present),NaN,NaN,NaN,2017.0,2017-1 task chair (Hawthorn)\n2000-1 Endura FA...
4,1029.0,15160 Yonge St,1,Aurora,ON,L4G 1M2,CAN,136632.0,12/1/11,1/31/22,...,2020.0,EDJ Standard – LVP & Carpet Tile (2016-Present),NaN,2020.0,SW Colony Buff/RockGarden (2009-Present),NaN,NaN,NaN,2000.0,"STANDARD\n2012 - (4) Stack guest chairs, (1) H..."

In [30]:
#merging physical locations data frame with the previously merged and cleaned data frames (top 50 and Amy's top 25 design info)
final_merge = pd.merge(pl_df_clean,top_25_merged,on='A')
final_merge

,A,Property Address,Suite,City,State,Zip,Country_x,Location Id,Original Occupancy,Lease Expiration,...,Best Month_y,Standard Layout,Layout Details,Current FA Offices (Not including Conference),Total Offices,Conference used to host Client meetings,Office Size,Non- Standard Items,Non Standard Finishes Description,Notes
0,2124.0,1807 S Washington St,111,Naperville,IL,60565,USA,2124.0,8/1/99,8/31/23,...,NaN,Yes,"(2) Similar sized offices, (1) conference room",2,2,Yes,1350,Yes,Built Ins/Wainscotting,NaN
1,2348.0,12300 Old Tesson Rd,100C,Saint Louis,MO,63128-2245,USA,198891.0,4/1/19,3/31/24,...,Y,Yes,"(1) Large FA office, (1) small office",2,2,No,1451,Yes,Built ins,NaN
2,3025.0,2004 COMMERCE DR N,215,PEACHTREE CITY,GA,30269-3559,USA,161835.0,9/1/15,8/31/25,...,NaN,Yes,Similar sized offices,2,3,Yes,1726,Yes,Tile Floor/Kitchenette,NaN
3,3151.0,1501 E Mockingbird,102,Victoria,TX,77904,USA,3151.0,4/1/01,8/31/29,...,Y,Yes,"(2) FA offices, 1 large conference",2,3,Yes,2491,Yes,Sidelights,NaN
4,3926.0,200 S Tattagona,NaN,Pensacola,FL,32502,USA,141749.0,1/1/13,12/31/22,...,Y,Yes,"(2) Large FA offices, 3 small offices",2,5,Yes,1500,Yes,Hardwood/Kitchenette,NaN
5,4454.0,19 W Main St,NaN,Shelby,OH,44875,USA,4454.0,7/1/89,7/31/24,...,NaN,Yes,Similar sized offices,1,2,Yes,1057,Yes,Built Ins/Wood Base/Kitchenette,NaN
6,5002.0,508 SECOND STREET,NaN,WEBSTER CITY,IA,50595,USA,5002.0,11/1/89,1/31/22,...,Y,Yes,GK expansion,3,7,Yes,1988,Yes,Tile/Custom Carpet/Wallpaper/Built Ins,NaN
7,5334.0,735 Essington Rd,101,Joliet,IL,60435,USA,5334.0,6/1/00,5/31/25,...,Y,No,"Large conference, large reception",2,2,Yes,1250,Yes,Wood baseKitchenette,NaN
8,5444.0,2550 Mosside Blvd,104,MONROEVILLE,PA,15146,USA,5444.0,12/1/92,11/30/22,...,Y,Yes,Pass through conference to 2nd office,1,2,Yes,1186,Yes,Custom Carpet/Non-Standard Paint,NaN
9,5506.0,415 N MCKINLEY ST,680,LITTLE ROCK,AR,72205,USA,140772.0,10/1/12,12/31/22,...,Y,Yes,"(1) Large FA office, (2) small offices",1,3,Yes,1420,Yes,Kitchenette,NaN
10,6411.0,2205 CONNECTICUT AVE,NaN,JOPLIN,MO,64804,USA,113129.0,12/1/10,4/30/21,...,NaN,Yes,"(1) Large FA office, 1 small offices, (1) lar...",1,3,Yes,2000,Yes,Tile/Custom Carpet/Built-Ins/Wood Base/wallpap...,NaN
11,6891.0,1325 Dry Creek Drive,200,Longmont,CO,80503,USA,6891.0,2/1/07,1/31/22,...,Y,Yes,NaN,1,2,Yes,1400,Yes,Tile/Custom Carpet/Kitchenette,"FP address not correct, assessed from photos"
12,7155.0,2629 Townsgate Road,135,Westlake Village,CA,91361,USA,7155.0,5/1/08,4/30/23,...,NaN,Yes,NaN,2,3,Yes,1366,Yes,Tile/Sidelights,NaN
13,7757.0,606 S 11th St,NaN,RICHMOND,TX,77469-3398,USA,7757.0,4/1/85,4/30/22,...,Y,Yes,"(1) Large FA office, (1) small office",1,2,No,1140,Yes,Built Ins/French Doors/Kitchenette,NaN
14,7822.0,3305 W. Nash St,NaN,Wilson,NC,27896,USA,7822.0,6/1/99,6/30/25,...,Y,Yes,"(1) Large FA office, 4 small BOA offices",1,5,No,1200,Yes,Tile/Custom Carpet/Built-Ins/Wood Base & chair...,NaN
15,8845.0,1701 Burnt Boat Dr,NaN,Bismarck,ND,58503,USA,8845.0,11/1/00,10/31/22,...,NaN,No,"Two Adequate size office, 4 small",2,6,Yes,2600,Yes,Tile/Custom Carpet,NaN
16,8858.0,2417 Meridian St,104,Bellingham,WA,98225-2426,USA,181972.0,12/1/17,11/30/22,...,NaN,Yes,"(2) Large FA offices, (2) small BOA offices, (...",2,5,Yes,1776,Yes,Built Ins/Custom Carpet/Kitchenette,NaN
17,8991.0,173 Court St,NaN,Woodland,CA,95695,USA,8991.0,4/1/99,4/30/24,...,NaN,No,"(2) Large FA offices, 2 small",2,5,Yes,1486,Yes,Hardwood/Custom Carpet/Sidelights/Kitchenette,NaN
18,9805.0,1377 Dominion Plaza,NaN,Tyler,TX,75703,USA,9805.0,12/1/00,11/30/20,...,NaN,Yes,"(1) Large FA office, (2) small offices",1,2,No,1600,Yes,Built Ins/Wood floor/Can lighting/custom carpe...,NaN
19,11962.0,105 S High St,NaN,West Chester,PA,19382,USA,11962.0,12/1/98,4/30/23,...,Y,Yes,"(1) Large FA office, 2 small",2,3,Yes,1245,Yes,Non Standard Plank/Custom Carpet/Glass walls/B...,NaN
20,12204.0,102 Old Fitzhugh Rd,100,Dripping Springs,TX,78620,USA,176256.0,3/1/17,8/31/22,...,Y,Yes,Similar sized offices,1,2,No,1200,Yes,Non Standard Plank/Custom wall accents/Glass w...,NaN
21,18122.0,6013 Harbour Park Dr,NaN,Midlothian,VA,23112,USA,18122.0,6/1/04,5/31/24,...,NaN,No,Shared Real Estate Layout,3,9,Yes,3334,Yes,Custom floor/glass walls/kitchenette/multiple ...,FAO not yet installed
22,19887.0,9855B Eagle Dr,NaN,Mont Belvieu,TX,77523-9847,USA,224799.0,9/1/20,9/30/27,...,NaN,No,Shared Real Estate Layout,1,11,Yes,3600,Yes,Custom plank/carpet/Glass partitions/lighting,NaN
23,25718.0,1710 W LAKE HOUSTON PKWY,190,KINGWOOD,TX,77339-2571,USA,135813.0,12/1/11,3/31/22,...,Y,Yes,NaN,2,4,Yes,1520,Yes,Hardwood/Custom Carpet/French Doors/Kitchenette,NaN
24,42006.0,22443 SE 240th Street,205,Maple Valley,WA,98038,USA,135054.0,9/1/11,8/31/22,...,Y,Yes,Similar sized offices,2,4,Yes,1700,Yes,Hardwood/Kitchenette,NaN

In [32]:
final_merge.to_csv('/Users/grizzlyjenkins/Personal Documents/top_25_clean.csv')